WITH PaymentsInEUR AS (
    SELECT
        p.AMOUNT,
        p.CURRENCY,
        p.TRANSACTION_DATE
    FROM
        PAYMENTS p
    LEFT JOIN
        BLACKLIST b ON p.USER_ID_SENDER = b.USER_ID
    INNER JOIN
        CURRENCIES c ON p.CURRENCY = c.CURRENCY_CODE
    WHERE
        b.USER_ID IS NULL
        AND c.END_DATE IS NULL
)
SELECT
    SUM(PIE.AMOUNT * COALESCE(er.EXCHANGE_RATE_TO_EUR, 1)) AS AMOUNT_EUR,
    PIE.TRANSACTION_DATE
FROM
    PaymentsInEUR PIE
LEFT JOIN
    CURRENCY_RATES er ON PIE.CURRENCY = er.CURRENCY_ID AND PIE.TRANSACTION_DATE = er.EXCHANGE_DATE
GROUP BY
    PIE.TRANSACTION_DATE;
